name: Feature request
description: Suggest an idea or improvement for deph
title: "[Feature]: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Tell us what you’d like to see and why.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem would this feature solve?
      placeholder: Describe the pain point or use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should deph behave? Include examples if helpful.
      placeholder: Describe the desired behavior, interface, or workflow

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you tried or considered

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any extra info, mockups, or references

