name: Publish Package

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Publish target"
        type: choice
        options: [testpypi, pypi]
        default: testpypi

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - run: python -m pip install build
      - run: python -m build
      - uses: actions/upload-artifact@v4
        with: { name: dist-artifacts, path: dist/ }

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
    environment:
      name: ${{ github.event.inputs.target }}
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dist-artifacts, path: dist/ }
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: ${{ github.event.inputs.target == 'testpypi' && 'https://test.pypi.org/legacy/' || '' }}
